version: 3.11.1
product: Web
productIcon: earth
section: Develop
sectionIcon: code
build: cd ../ && npm install && npm run build
develop: cd ../ && npm run dev
variables:
  repositoryUrl: https://www.secrz.de/bitbucket/projects/CAKE/repos/showroom/,
  bundleDownloadUrl: https://www.secrz.de/bitbucket/rest/api/latest/projects/CAKE/repos/phoenix/archive?at=refs%2Ftags%2Fv
  sourceDownloadUrl: https://www.secrz.de/bitbucket/rest/api/latest/projects/CAKE/repos/phoenix/archive?at=refs%2Ftags%2Fv
  npmPackageUrl: https://repo.schwarz/artifactory/webapp/#/artifacts/browse/tree/General/cake-npm
  npmRegistryUrl: https://pkgs.dev.azure.com/schwarzit/_packaging/cake/npm/registry/,
  contactMailAddress: cake@lidl.com

