version: 4.1.0
product: Web
productIcon: earth
section: Develop
sectionIcon: code
build: cd ../ && npm install && npm run build
develop: cd ../ && npm run dev
variables:
  npmPackageName: "@cake-hub/web-css_framework"
  repositoryUrl: https://github.com/cake-hub/web-css_framework
  bundleDownloadUrl: https://github.com/cake-hub/web-css_framework/archive/master.zip
  sourceDownloadUrl: https://github.com/cake-hub/web-css_framework/archive/master.zip
  npmPackageUrl: https://www.npmjs.com/package/@cake-hub/web-css_framework
  npmRegistryUrl: https://registry.npmjs.org/

